#!/bin/bash

TEMPFILE=/tmp/params-$$
GETTEXT="gettext -d transact_ui"

set_dialog(){
which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog
echo $DIALOG
}

ui_main() {
    NAME="Send Money"
    DIALOG=$(set_dialog)


while true
do

	STATUS=$(./transact -s)
	if [[ $STATUS != *"OK" ]];
        then
        echo $STATUS
	$DIALOG --title "`$GETTEXT \"Error!\"`" --msgbox "$STATUS" 6 20
        exit 
	fi
	
	
	
	$DIALOG --title "$NAME" --inputbox "`gettext \"Enter the sender's account:\"`" 8 35 2> $TEMPFILE
	SENDER=$(cat $TEMPFILE)
	
	$DIALOG --title "$NAME" --inputbox "`gettext \"Enter the receiver's account:\"`" 8 35 2> $TEMPFILE
        RECEIVER=$(cat $TEMPFILE)

	$DIALOG --title "$NAME" --inputbox "`gettext \"Amount:\"`" 8 35 2> $TEMPFILE
        AMOUNT=$(cat $TEMPFILE)

	$DIALOG --title "$NAME" --inputbox "`gettext \"Password:\"`" 8 35 2> $TEMPFILE
        PASSWD=$(cat $TEMPFILE)
	
	TRANSACTION=$(./transact -a $SENDER $RECEIVER $AMOUNT $PASSWD)
	echo $TRANSACTION

	MSG="`$GETTEXT \"Transaction ID is:\"`"
	MSG+="$TRANSACTION"
	$DIALOG --title "`$GETTEXT \"TRANSACTION number is:\"`" --msgbox "$TRANSACTION" 6 20
	
	
	MSG="`$GETTEXT \"Do you want to make another transaction?\"`"
	$DIALOG --title "$NAME" --yesno "$MSG" 10 50 || exit	
	

done

}

ui_main
